import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import {
  CapitalizePipe,
  ExtractFileTypeFromPath,
  MaskText,
  NameInitials,
  Ordinal,
  ReplaceUnderscore,
  StripUnderscore,
  TransformAmount,
  TransformCamelCase,
  TransformDayTime,
  TransformRef,
  TransformTime,
  TransformToNaira,
  SmartTitleCase,
} from './index';

@NgModule({
  declarations: [
    StripUnderscore,
    TransformTime,
    Ordinal,
    TransformRef,
    TransformToNaira,
    TransformDayTime,
    TransformCamelCase,
    NameInitials,
    ExtractFileTypeFromPath,
    MaskText,
    ReplaceUnderscore,
    CapitalizePipe,
    TransformAmount,
    SmartTitleCase,
    // ExtractFileType,
  ],
  imports: [CommonModule],
  exports: [
    StripUnderscore,
    TransformTime,
    Ordinal,
    TransformRef,
    TransformToNaira,
    TransformDayTime,
    TransformCamelCase,
    NameInitials,
    ReplaceUnderscore,
    TransformAmount,
    MaskText,
    CapitalizePipe,
    SmartTitleCase,
    ExtractFileTypeFromPath,
  ],
})
export class CustomPipeModule {}
