export const environment = {
  production: false,
  envName: 'DEV',
  // url: 'https://staging.api.fees.ng/api/v2/',
  // url: 'https://fees-ng-be-staging.onrender.com/api/v2/',
  // url: 'https://dev.api.fees.ng/api/v2/',
  baseUrl: 'http://localhost:45000/api/v2/',
  // examportalUrl: 'https://staging.api.examportal.ng/api/v1/',
  examportalKey: 'sllwjKQ9UiUb',
  idleTimeAllowed: 90000,
  idleTimeout: 5,
  squadGateway: true,
  isSandbox: true,
  monifyUrl: 'https://sandbox.sdk.monnify.com/checkout/',
};
